/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpoint.view;

/**
 *
 * @author Rangel
 */
public class FrClockInOut extends javax.swing.JFrame {

    /**
     * Creates new form FrClockInOut
     */
    public FrClockInOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClockInOut = new javax.swing.JPanel();
        lblIconUser = new javax.swing.JLabel();
        lblNameUser = new javax.swing.JLabel();
        lblDepartamentUser = new javax.swing.JLabel();
        lblTittleClockInOut = new javax.swing.JLabel();
        btnClockInOut = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/usuario-do-circulo (3).png"))); // NOI18N

        lblNameUser.setText("Rangel Leônidas Silva");

        lblDepartamentUser.setText("Information Technology");

        lblTittleClockInOut.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblTittleClockInOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittleClockInOut.setText("Clock In/Out");
        lblTittleClockInOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnClockInOut.setText("Clock In / Out");

        lblDate.setText("Monday - 09/22/2026");

        lblHour.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        lblHour.setText("10:20");

        javax.swing.GroupLayout pnlClockInOutLayout = new javax.swing.GroupLayout(pnlClockInOut);
        pnlClockInOut.setLayout(pnlClockInOutLayout);
        pnlClockInOutLayout.setHorizontalGroup(
            pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClockInOutLayout.createSequentialGroup()
                .addGroup(pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClockInOutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClockInOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTittleClockInOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlClockInOutLayout.createSequentialGroup()
                                .addComponent(lblIconUser)
                                .addGap(18, 18, 18)
                                .addGroup(pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNameUser)
                                    .addComponent(lblDepartamentUser))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlClockInOutLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate)
                            .addComponent(lblHour))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlClockInOutLayout.setVerticalGroup(
            pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClockInOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittleClockInOut)
                .addGap(18, 18, 18)
                .addGroup(pnlClockInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClockInOutLayout.createSequentialGroup()
                        .addComponent(lblNameUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDepartamentUser))
                    .addComponent(lblIconUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClockInOut, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlClockInOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlClockInOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClockInOut;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepartamentUser;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblTittleClockInOut;
    private javax.swing.JPanel pnlClockInOut;
    // End of variables declaration//GEN-END:variables
}
