/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpoint.view;

/**
 *
 * @author Rangel
 */
public class FrCrudAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form FrCrudAdministrator
     */
    public FrCrudAdministrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitlePanelAdm = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        pnlUsers = new javax.swing.JPanel();
        lblIconUsers = new javax.swing.JLabel();
        lblNumberUsers = new javax.swing.JLabel();
        pnlTasks = new javax.swing.JPanel();
        lblIconTask = new javax.swing.JLabel();
        lblNumberTasks = new javax.swing.JLabel();
        pnlProjects = new javax.swing.JPanel();
        lblIconProjects = new javax.swing.JLabel();
        lblNumberProjects = new javax.swing.JLabel();
        pnlUsersGroup = new javax.swing.JPanel();
        lblIconUsersGroup = new javax.swing.JLabel();
        lblNumberTeam = new javax.swing.JLabel();
        pnlPanelCrud = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnRegisterUser = new javax.swing.JButton();
        btnRegisterTask = new javax.swing.JButton();
        btnRegisterProject = new javax.swing.JButton();
        btnRegisterTeam = new javax.swing.JButton();
        btnViewProjects = new javax.swing.JButton();
        btnViewTask1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePanelAdm.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblTitlePanelAdm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePanelAdm.setText("Panel Administrator");
        lblTitlePanelAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/usuario-do-circulo (3).png"))); // NOI18N
        lblIconUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSearch.setForeground(new java.awt.Color(102, 102, 102));

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/procurar.png"))); // NOI18N

        pnlUsers.setBackground(new java.awt.Color(204, 204, 204));
        pnlUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblIconUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/usuario-do-circulo (3).png"))); // NOI18N

        lblNumberUsers.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNumberUsers.setForeground(new java.awt.Color(0, 0, 0));
        lblNumberUsers.setText("28");

        javax.swing.GroupLayout pnlUsersLayout = new javax.swing.GroupLayout(pnlUsers);
        pnlUsers.setLayout(pnlUsersLayout);
        pnlUsersLayout.setHorizontalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblIconUsers))
        );
        pnlUsersLayout.setVerticalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberUsers)
                .addContainerGap())
        );

        pnlTasks.setBackground(new java.awt.Color(204, 204, 204));
        pnlTasks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlTasks.setAlignmentX(1.0F);
        pnlTasks.setAlignmentY(1.0F);

        lblIconTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/nota.png"))); // NOI18N

        lblNumberTasks.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNumberTasks.setForeground(new java.awt.Color(0, 0, 0));
        lblNumberTasks.setText("100");

        javax.swing.GroupLayout pnlTasksLayout = new javax.swing.GroupLayout(pnlTasks);
        pnlTasks.setLayout(pnlTasksLayout);
        pnlTasksLayout.setHorizontalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconTask)
                .addContainerGap())
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberTasks)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlTasksLayout.setVerticalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberTasks)
                .addContainerGap())
        );

        pnlProjects.setBackground(new java.awt.Color(204, 204, 204));
        pnlProjects.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlProjects.setAlignmentX(1.0F);
        pnlProjects.setAlignmentY(1.0F);

        lblIconProjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/projeto-de-diagrama.png"))); // NOI18N

        lblNumberProjects.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNumberProjects.setForeground(new java.awt.Color(0, 0, 0));
        lblNumberProjects.setText("36");

        javax.swing.GroupLayout pnlProjectsLayout = new javax.swing.GroupLayout(pnlProjects);
        pnlProjects.setLayout(pnlProjectsLayout);
        pnlProjectsLayout.setHorizontalGroup(
            pnlProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectsLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblIconProjects)
                .addContainerGap())
            .addGroup(pnlProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberProjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProjectsLayout.setVerticalGroup(
            pnlProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberProjects)
                .addContainerGap())
        );

        pnlUsersGroup.setBackground(new java.awt.Color(204, 204, 204));
        pnlUsersGroup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlUsersGroup.setAlignmentX(1.0F);
        pnlUsersGroup.setAlignmentY(1.0F);

        lblIconUsersGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/users-group.png"))); // NOI18N

        lblNumberTeam.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNumberTeam.setForeground(new java.awt.Color(0, 0, 0));
        lblNumberTeam.setText("9");

        javax.swing.GroupLayout pnlUsersGroupLayout = new javax.swing.GroupLayout(pnlUsersGroup);
        pnlUsersGroup.setLayout(pnlUsersGroupLayout);
        pnlUsersGroupLayout.setHorizontalGroup(
            pnlUsersGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsersGroupLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(lblIconUsersGroup)
                .addContainerGap())
            .addGroup(pnlUsersGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberTeam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUsersGroupLayout.setVerticalGroup(
            pnlUsersGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconUsersGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberTeam)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitlePanelAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlUsersGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitlePanelAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(lblIconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlUsersGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPanelCrud.setBackground(new java.awt.Color(204, 204, 204));
        pnlPanelCrud.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/logoTest.jpg"))); // NOI18N
        lblIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDashboard.setText("Dashboard");

        btnRegisterUser.setText("Register User");

        btnRegisterTask.setText("Register Task");

        btnRegisterProject.setText("Register Project");

        btnRegisterTeam.setText("Register Team");

        btnViewProjects.setText("View Projects");

        btnViewTask1.setText("View Tasks");

        javax.swing.GroupLayout pnlPanelCrudLayout = new javax.swing.GroupLayout(pnlPanelCrud);
        pnlPanelCrud.setLayout(pnlPanelCrudLayout);
        pnlPanelCrudLayout.setHorizontalGroup(
            pnlPanelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelCrudLayout.createSequentialGroup()
                        .addGroup(pnlPanelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIcon)
                            .addComponent(btnRegisterProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnViewTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPanelCrudLayout.setVerticalGroup(
            pnlPanelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon)
                .addGap(40, 40, 40)
                .addComponent(btnDashboard)
                .addGap(76, 76, 76)
                .addComponent(btnRegisterUser)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterTask)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterProject)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterTeam)
                .addGap(18, 18, 18)
                .addComponent(btnViewTask1)
                .addGap(18, 18, 18)
                .addComponent(btnViewProjects)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainPanelLayout = new javax.swing.GroupLayout(pnlMainPanel);
        pnlMainPanel.setLayout(pnlMainPanelLayout);
        pnlMainPanelLayout.setHorizontalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPanelCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainPanelLayout.setVerticalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPanelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCrudAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCrudAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCrudAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCrudAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCrudAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnRegisterProject;
    private javax.swing.JButton btnRegisterTask;
    private javax.swing.JButton btnRegisterTeam;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JButton btnViewProjects;
    private javax.swing.JButton btnViewTask1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconProjects;
    private javax.swing.JLabel lblIconTask;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblIconUsers;
    private javax.swing.JLabel lblIconUsersGroup;
    private javax.swing.JLabel lblNumberProjects;
    private javax.swing.JLabel lblNumberTasks;
    private javax.swing.JLabel lblNumberTeam;
    private javax.swing.JLabel lblNumberUsers;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitlePanelAdm;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JPanel pnlPanelCrud;
    private javax.swing.JPanel pnlProjects;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JPanel pnlUsersGroup;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
