/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpoint.view;

/**
 *
 * @author Rangel
 */
public class FrDailyPoint extends javax.swing.JFrame {

    /**
     * Creates new form FrDailyPoint
     */
    public FrDailyPoint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTittleDailyPoint = new javax.swing.JLabel();
        lblIconClock = new javax.swing.JLabel();
        lblEntryOne = new javax.swing.JLabel();
        lblHourEntryOne = new javax.swing.JLabel();
        lblIconClock1 = new javax.swing.JLabel();
        lblOutOne = new javax.swing.JLabel();
        lblHourOutOne = new javax.swing.JLabel();
        lblIconClock2 = new javax.swing.JLabel();
        lblEntryTwo = new javax.swing.JLabel();
        lblHourEntryTwo = new javax.swing.JLabel();
        lblIconClock3 = new javax.swing.JLabel();
        lblOutTwo = new javax.swing.JLabel();
        lblHourOutTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTittleDailyPoint.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblTittleDailyPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittleDailyPoint.setText("Daily Point");
        lblTittleDailyPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIconClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/relogio-nove.png"))); // NOI18N

        lblEntryOne.setText("Entry One:");

        lblHourEntryOne.setText("10:20");

        lblIconClock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/relogio-nove.png"))); // NOI18N

        lblOutOne.setText("Out One:");

        lblHourOutOne.setText("12:50");

        lblIconClock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/relogio-nove.png"))); // NOI18N

        lblEntryTwo.setText("Entry Two:");

        lblHourEntryTwo.setText("14:20");

        lblIconClock3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/relogio-nove.png"))); // NOI18N

        lblOutTwo.setText("Out Two:");

        lblHourOutTwo.setText("17:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTittleDailyPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconClock2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEntryTwo)
                        .addGap(18, 18, 18)
                        .addComponent(lblHourEntryTwo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconClock3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOutTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHourOutTwo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconClock1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOutOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHourOutOne))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconClock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEntryOne)
                        .addGap(18, 18, 18)
                        .addComponent(lblHourEntryOne)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittleDailyPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconClock)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEntryOne)
                        .addComponent(lblHourEntryOne)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconClock1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOutOne)
                        .addComponent(lblHourOutOne)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconClock2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEntryTwo)
                        .addComponent(lblHourEntryTwo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconClock3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOutTwo)
                        .addComponent(lblHourOutTwo)))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEntryOne;
    private javax.swing.JLabel lblEntryTwo;
    private javax.swing.JLabel lblHourEntryOne;
    private javax.swing.JLabel lblHourEntryTwo;
    private javax.swing.JLabel lblHourOutOne;
    private javax.swing.JLabel lblHourOutTwo;
    private javax.swing.JLabel lblIconClock;
    private javax.swing.JLabel lblIconClock1;
    private javax.swing.JLabel lblIconClock2;
    private javax.swing.JLabel lblIconClock3;
    private javax.swing.JLabel lblOutOne;
    private javax.swing.JLabel lblOutTwo;
    private javax.swing.JLabel lblTittleDailyPoint;
    // End of variables declaration//GEN-END:variables
}
