/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpoint.view;

/**
 *
 * @author Rangel
 */
public class FrRegisterTask extends javax.swing.JFrame {

    /**
     * Creates new form FrRegisterTask
     */
    public FrRegisterTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgState = new javax.swing.ButtonGroup();
        lblTitleTask = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNameTask = new javax.swing.JLabel();
        txtNameTask = new javax.swing.JTextField();
        lblDescriptionTask = new javax.swing.JLabel();
        txtDescriptionTask = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        rdbNotStarted = new javax.swing.JRadioButton();
        rdbInProgress = new javax.swing.JRadioButton();
        rdbCompleted = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnViewTask1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleTask.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblTitleTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTask.setText("Register Task");
        lblTitleTask.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNameTask.setText("Name task:");

        lblDescriptionTask.setText("Description:");

        lblState.setText("State:");

        bgState.add(rdbNotStarted);
        rdbNotStarted.setText("Not started");

        bgState.add(rdbInProgress);
        rdbInProgress.setText("In progress");

        bgState.add(rdbCompleted);
        rdbCompleted.setText("Completed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescriptionTask)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNameTask)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameTask))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescriptionTask)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblState)
                                .addGap(18, 18, 18)
                                .addComponent(rdbNotStarted)
                                .addGap(18, 18, 18)
                                .addComponent(rdbInProgress)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCompleted)))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameTask)
                    .addComponent(txtNameTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDescriptionTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescriptionTask, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(rdbNotStarted)
                    .addComponent(rdbInProgress)
                    .addComponent(rdbCompleted))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnSave.setText("Save");

        btnCancel.setText("Cancel");

        btnViewTask1.setText("View Tasks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewTask1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleTask, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnViewTask1))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgState;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewTask1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescriptionTask;
    private javax.swing.JLabel lblNameTask;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitleTask;
    private javax.swing.JRadioButton rdbCompleted;
    private javax.swing.JRadioButton rdbInProgress;
    private javax.swing.JRadioButton rdbNotStarted;
    private javax.swing.JTextField txtDescriptionTask;
    private javax.swing.JTextField txtNameTask;
    // End of variables declaration//GEN-END:variables
}
