/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpoint.view;
import com.mycompany.cpoint.dao.UserDAO;
import com.mycompany.cpoint.model.User;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.mycompany.cpoint.controller.TeamController;
import com.mycompany.cpoint.exception.ValidationException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Rangel
 */
public class FrRegisterTeam extends javax.swing.JFrame {
    private final List<User> selectedMembers = new ArrayList<>();

    /**
     * Creates new form FrRegisterTeam
     */
    public FrRegisterTeam() {
    initComponents();
    loadUsers();
}

private void loadUsers() {
    try {
        UserDAO userDAO = new UserDAO();
        for (User user : userDAO.findAll()) {
            cmbUsers.addItem(user);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar usuários: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblTitleTeam = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNameTeam = new javax.swing.JLabel();
        txtNameTeam = new javax.swing.JTextField();
        btnAddMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        btnListMembers = new javax.swing.JButton();
        cmbUsers = new javax.swing.JComboBox<>();
        lblSelectMember = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cpoint/resources/logoTest.jpg"))); // NOI18N
        lblIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitleTeam.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblTitleTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTeam.setText("Register Team");
        lblTitleTeam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNameTeam.setText("Name team:");

        btnAddMember.setText("Add member");
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });

        btnDeleteMember.setText("Delete member");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });

        btnListMembers.setText("List Members");
        btnListMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListMembersActionPerformed(evt);
            }
        });

        lblSelectMember.setText("Select Member:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameTeam)
                            .addComponent(lblSelectMember))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUsers, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameTeam))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameTeam)
                    .addComponent(txtNameTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectMember))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMember)
                    .addComponent(btnDeleteMember)
                    .addComponent(btnListMembers))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitleTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemberActionPerformed
        User selected = (User) cmbUsers.getSelectedItem();

    if (selected == null) {
        JOptionPane.showMessageDialog(this, "Selecione um usuário primeiro.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (selectedMembers.contains(selected)) {
        JOptionPane.showMessageDialog(this, "Esse usuário já foi adicionado ao time.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    selectedMembers.add(selected);
    JOptionPane.showMessageDialog(this, selected + " adicionado ao time.");
    }//GEN-LAST:event_btnAddMemberActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        User selected = (User) cmbUsers.getSelectedItem();

    if (selected == null) {
        JOptionPane.showMessageDialog(this, "Selecione um usuário primeiro.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (selectedMembers.remove(selected)) {
        JOptionPane.showMessageDialog(this, selected + " removido do time.");
    } else {
        JOptionPane.showMessageDialog(this, "Esse usuário não está no time.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void btnListMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListMembersActionPerformed
        if (selectedMembers.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum membro adicionado ainda.");
        return;
    }

    StringBuilder sb = new StringBuilder("Membros do time:\n");
    for (User member : selectedMembers) {
        sb.append("- ").append(member).append("\n");
    }
    JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnListMembersActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String name = txtNameTeam.getText();
    TeamController controller = new TeamController();

    try {
        controller.registerTeam(name, selectedMembers);
        JOptionPane.showMessageDialog(this, "Time cadastrado com sucesso!");
        selectedMembers.clear();
        txtNameTeam.setText("");
    } catch (ValidationException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Erro de validação", JOptionPane.WARNING_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar no banco: " + ex.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> new FrRegisterTeam().setVisible(true));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnListMembers;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<User> cmbUsers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblNameTeam;
    private javax.swing.JLabel lblSelectMember;
    private javax.swing.JLabel lblTitleTeam;
    private javax.swing.JTextField txtNameTeam;
    // End of variables declaration//GEN-END:variables
}
